# Generated by Django 3.2.13 on 2022-06-14 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_status', models.CharField(choices=[('Open', 'Open'), ('Responded', 'Responded'), ('Complete', 'Complete')], default=1, max_length=15)),
            ],
        ),
    ]
