# Generated by Django 3.2.13 on 2022-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='podcast_url',
            field=models.URLField(max_length=255),
        ),
    ]
